name: Bump package version

on:
  issue_comment:
    types: [ created ]
  workflow_call:

jobs:
  bump:
    name: Bump version triggered by PR comment
    if: |
      github.event.issue.pull_request &&
      contains( fromJSON( '[ "collaborator", "member", "owner" ]' ), github.event.comment.author_association ) &&
      startsWith( github.event.comment.body, 'bump' )

    runs-on: ubuntu-latest
    steps:
      - name: Get the branch of the PR
        id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup Github Action user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"

      - name: Convert comment to lowercase
        id: lowercase-comment
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.event.comment.body }}
          
      - name: Bump version
        run: |
          if [ ${{ contains( steps.lowercase-comment.outputs.lowercase, 'minor' ) }} ]; then
            npm version minor -m "chore: set version to %s"
          elif [ ${{ contains( steps.lowercase-comment.outputs.lowercase, 'major' ) }} ]; then
            npm version major -m "chore: set version to %s"
          else
            npm version patch -m "chore: set version to %s"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.comment-branch.outputs.head_ref }}
