name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@8530928916aaef40f59e6f221989ccb31f5759e7 
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@8d2cf95286e3dd3d016d478187b93b57af29fd2d
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
