name: Deploy using Docker via SSH

on:
  workflow_call:

jobs:
  ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run commands in remote host
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker stop ${{ github.event.repository.name }} || true \\
          && docker rm ${{ github.event.repository.name }} || true \\
          && docker image prune -a -f \\
          && docker run -d --net ${{ secrets.DOCKER_NETWORK }} --env DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} --name ${{ github.event.repository.name }} ghcr.io/${{ github.repository }}:latest"
