name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222 
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@f9efed53cc1b0364ba947400ac02042bbbaac7fc
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
