name: Deploy using Docker via SSH

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login via SSH
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Create a file
        run: echo "Test" >> ~/code/testfile