name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@27135e314dd1818f797af1db9dae03a9f045786b 
        with:
          submodules: true

      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: false
          build-args: GITHUB_PAT=${{ secrets.GH_TOKEN }}
