name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@7cdaf2fbc075e6f3b9ca94cfd6cec5adc8a75622 
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@0f847266c302569530c95bfa228489494c43b002
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
