name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@473055ba18d6d2da209cd46110aadb9275e3194e 
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
