name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 
        with:
          submodules: true

      - name: Build Docker image
        uses: docker/build-push-action@817ed59f97d2974e2c1d92f170242f52fd3feae4
        with:
          context: .
          push: false
          build-args: GITHUB_PAT=${{ secrets.GH_TOKEN }}
