name: Build Docker image

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9 
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@4c1b68d83ad20cc1a09620ca477d5bbbb5fa14d0
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
